"""
Django settings for primary_server project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os.path
import ast
import json
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#
# Change the value following this comment to the path of your working
# copy of the starcoder-experiments repository.  The path can be
# absolute, like this:
#
#   STARCODER_EXPERIMENTS_PATH = "/some/path/starcoder-experiments"
#
# or it can be relative to the cih-servers installation. But don't do
# this:
#
#   STARCODER_EXPERIMENTS_PATH = "../starcoder-experiments"
#
# because that's sensitive to where you invoke commands from.  Instead,
# do this, which has the same intended effect and is stable:
#
#STARCODER_EXPERIMENTS_PATH = os.path.join(BASE_DIR.parent, "starcoder-experiments")

#SCHEMAS = {}
#with open(os.path.join(STARCODER_EXPERIMENTS_PATH, "custom.py"), "rt") as c_ifd:    
#    tree = ast.parse(c_ifd.read())
#    for expr in tree.body:
#        if len(getattr(expr, "targets", [])) == 1 and expr.targets[0].id == "EXPERIMENTS":
#            for k, v in ast.literal_eval(expr.value).items():
#                with open(os.path.join(STARCODER_EXPERIMENTS_PATH, v["SCHEMA"]), "rt") as s_ifd:
#                    SCHEMAS[k] = json.loads(s_ifd.read())
#            break
#PROJECT_IDS = list(SCHEMAS.keys())

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '439ll50p8p(u3kfh11br!3xw=@=o*0u4%fl@%j(nv=16g60=i4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'interact',
    #'turkle',
    #'django_nose',
    #'guardian',
    #'admin_auto_filters',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'primary_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'primary_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST' : 'localhost',
        'NAME': 'cih',
        'USER': 'cih',
        'PASSWORD' : 'st4rcod3r',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
